


package org.hsqldb;

public interface OpTypes {

    int NONE                 = 0,
        VALUE                = 1,     
        COLUMN               = 2,     
        COALESCE             = 3,
        DEFAULT              = 4,
        SIMPLE_COLUMN        = 5,
        VARIABLE             = 6,
        PARAMETER            = 7,
        DYNAMIC_PARAM        = 8,
        TRANSITION_VARIABLE  = 9,
        DIAGNOSTICS_VARIABLE = 10,
        ASTERISK             = 11,
        SEQUENCE             = 12,
        SEQUENCE_CURRENT     = 13,
        ROWNUM               = 14,
        ARRAY                = 19,
        MULTISET             = 20,
        SCALAR_SUBQUERY      = 21,    
        ROW_SUBQUERY         = 22,
        TABLE_SUBQUERY       = 23,
        RECURSIVE_SUBQUERY   = 24,
        ROW                  = 25,    
        VALUELIST            = 26,
        FUNCTION             = 27,
        SQL_FUNCTION         = 28,
        ROUTINE_FUNCTION     = 29,
        TABLE                = 30,
        NEGATE               = 31,    
        ADD                  = 32,
        SUBTRACT             = 33,
        MULTIPLY             = 34,
        DIVIDE               = 35,
        CONCAT               = 36,    
        LIKE_ARG             = 37,
        CASEWHEN_COALESCE    = 38,
        EQUAL                = 41,    
        GREATER_EQUAL        = 42,
        GREATER              = 43,
        SMALLER              = 44,
        SMALLER_EQUAL        = 45,
        NOT_EQUAL            = 46,
        IS_NULL              = 47,
        NOT                  = 48,    
        AND                  = 49,
        OR                   = 50,
        ALL_QUANTIFIED       = 51,    
        ANY_QUANTIFIED       = 52,
        LIKE                 = 53,    
        IN                   = 54,
        EXISTS               = 55,
        OVERLAPS             = 56,
        UNIQUE               = 57,
        NOT_DISTINCT         = 58,
        MATCH_SIMPLE         = 59,
        MATCH_PARTIAL        = 60,
        MATCH_FULL           = 61,
        MATCH_UNIQUE_SIMPLE  = 62,
        MATCH_UNIQUE_PARTIAL = 63,
        MATCH_UNIQUE_FULL    = 64,
        CONTAINS             = 65,
        COUNT                = 71,    
        SUM                  = 72,
        MIN                  = 73,
        MAX                  = 74,
        AVG                  = 75,
        EVERY                = 76,
        SOME                 = 77,
        STDDEV_POP           = 78,
        STDDEV_SAMP          = 79,
        VAR_POP              = 80,
        VAR_SAMP             = 81,
        ARRAY_AGG            = 82,
        GROUP_CONCAT         = 83,
        PREFIX               = 84,
        MEDIAN               = 85,
        CAST                 = 91,    
        ZONE_MODIFIER        = 92,
        CASEWHEN             = 93,
        ORDER_BY             = 94,
        LIMIT                = 95,
        ALTERNATIVE          = 96,
        MULTICOLUMN          = 97,
        USER_AGGREGATE       = 98,
        ARRAY_ACCESS         = 99,
        ARRAY_SUBQUERY       = 100
    ;
}
